repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --skip-string-normalization]
        files: ^apps/backend/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]
        files: ^apps/backend/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        files: ^apps/backend/.*\.py$

  # TypeScript/JavaScript formatting and linting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^apps/frontend/.*\.(js|jsx|ts|tsx|json|css|md)$
        args: [--write]
        additional_dependencies:
          - prettier@4.0.0-alpha.8
          - '@prettier/plugin-xml@3.1.1'

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.9.0
    hooks:
      - id: eslint
        files: ^apps/frontend/.*\.(js|jsx|ts|tsx)$
        args: [--fix]
        additional_dependencies:
          - eslint@9.9.0
          - '@eslint/js@9.9.0'
          - 'typescript-eslint@8.0.1'
          - 'eslint-plugin-react-hooks@5.1.0-rc.0'
          - 'eslint-plugin-react-refresh@0.4.9'

  # General file formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements
