name: Terraform Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: "dev"
      aws_region:
        description: 'AWS region to deploy to'
        required: true
        type: string
        default: "eu-north-1"
      instance_type:
        description: 'EC2 instance type'
        required: true
        type: string
        default: "t2.micro"
    outputs:
      instance_ip:
        description: "The public IP of the created EC2 instance"
        value: ${{ jobs.terraform.outputs.instance_ip }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ inputs.aws_region }}
      ENVIRONMENT: ${{ inputs.environment }}
      INSTANCE_TYPE: ${{ inputs.instance_type }}
    outputs:
      instance_ip: ${{ steps.terraform_output.outputs.instance_ip }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="instance_type=${{ env.INSTANCE_TYPE }}" \
            -var="project_name=vista-${{ env.ENVIRONMENT }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          cd terraform
          terraform apply -auto-approve \
            -var="aws_region=${{ env.AWS_REGION }}" \
            -var="instance_type=${{ env.INSTANCE_TYPE }}" \
            -var="project_name=vista-${{ env.ENVIRONMENT }}"

      - name: Save Terraform Output
        id: terraform_output
        run: |
          cd terraform
          echo "instance_ip=$(terraform output -raw instance_ip)" >> $GITHUB_OUTPUT
