name: Terraform Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: "dev"
      aws_region:
        description: 'AWS region to deploy to'
        required: true
        type: string
        default: "eu-north-1"
      instance_type:
        description: 'EC2 instance type'
        required: true
        type: string
        default: "t2.micro"
    outputs:
      instance_ip:
        description: "The public IP of the created EC2 instance"
        value: ${{ jobs.terraform.outputs.instance_ip }}

jobs:
  test:
    # Run tests first
    uses: ./.github/workflows/backend-test.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  terraform:
    # Run terraform after tests pass
    needs: test
    uses: ./.github/workflows/backend-terraform.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      instance_type: ${{ github.event.inputs.instance_type || 't2.micro' }}
      use_access_keys: ${{ github.event.inputs.use_access_keys || 'false' }}
    secrets: inherit

  build:
    # Build after infrastructure is ready
    needs: terraform
    uses: ./.github/workflows/backend-build.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  deploy:
    # Deploy after build is complete
    needs: [build, terraform]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      instance_ip: ${{ needs.terraform.outputs.instance_ip }}
    secrets: inherit
