name: Terraform Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
        default: "dev"
      aws_region:
        description: 'AWS region to deploy to'
        required: true
        type: string
        default: "eu-north-1"
      instance_type:
        description: 'EC2 instance type'
        required: true
        type: string
        default: "t2.micro"
    outputs:
      instance_ip:
        description: "The public IP of the created EC2 instance"
        value: ${{ jobs.terraform.outputs.instance_ip }}

jobs:
  terraform:
    # Run terraform after tests pass
    uses: ./.github/workflows/backend-terraform.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      instance_type: ${{ github.event.inputs.instance_type || 't2.micro' }}
      use_access_keys: ${{ github.event.inputs.use_access_keys || 'false' }}
    secrets: inherit
