name: "Deploy Backend"

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'terraform/**'
      - '.github/workflows/deploy-backend.yml'
      - '.github/workflows/backend-*.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        default: "dev"
        options:
        - "dev"
        - "prod"
      aws_region:
        description: 'AWS region to deploy to'
        required: true
        type: choice
        default: "eu-north-1"
        options:
        - "eu-north-1"
        - "us-east-1"
      instance_type:
        description: 'EC2 instance type'
        required: true
        type: choice
        default: "t3.micro"
        options:
        - "t3.micro"
        - "t3.small"
      existing_vpc_id:
        description: 'ID of an existing VPC to use (leave empty to use default VPC)'
        required: false
        type: string
        default: "vpc-0dafdafe8c44a431c"
      existing_subnet_id:
        description: 'ID of an existing subnet to use (leave empty to auto-select a public subnet)'
        required: false
        type: string
        default: "subnet-05917f37a18a5a172"

# These permissions are needed to interact with GitHub's OIDC Token endpoint for AWS authentication
permissions:
  id-token: write  # Required for requesting the JWT
  contents: read   # Required for actions/checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/backend-test.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  terraform:
    needs: test
    uses: ./.github/workflows/backend-terraform.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      instance_type: ${{ github.event.inputs.instance_type || 't3.micro' }}
      existing_vpc_id: ${{ github.event.inputs.existing_vpc_id || 'vpc-0dafdafe8c44a431c' }}
      existing_subnet_id: ${{ github.event.inputs.existing_subnet_id || 'subnet-05917f37a18a5a172' }}
    secrets: inherit

  build:
    needs: terraform
    uses: ./.github/workflows/backend-build.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  deploy:
    needs: [build, terraform]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      instance_ip: ${{ needs.terraform.outputs.instance_ip }}
    secrets: inherit
