name: "Deploy Backend"

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/backend/**'
      - 'terraform/**'
      - '.github/workflows/deploy-backend.yml'
      - '.github/workflows/backend-*.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        default: "dev"
        options:
        - "dev"
        - "prod"
      aws_region:
        description: 'AWS region to deploy to'
        required: true
        type: choice
        default: "eu-north-1"
        options:
        - "eu-north-1"
        - "us-east-1"
      instance_type:
        description: 'EC2 instance type'
        required: true
        type: choice
        default: "t2.micro"
        options:
        - "t2.micro"
        - "t2.small"
        - "t2.medium"

# These permissions are needed to interact with GitHub's OIDC Token endpoint for AWS authentication
permissions:
  id-token: write  # Required for requesting the JWT
  contents: read   # Required for actions/checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/backend-test.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  build:
    needs: test
    uses: ./.github/workflows/backend-build.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
    secrets: inherit

  terraform:
    # needs: build
    uses: ./.github/workflows/backend-terraform.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      instance_type: ${{ github.event.inputs.instance_type || 't2.micro' }}
    secrets: inherit

  deploy:
    needs: [build, terraform]
    uses: ./.github/workflows/backend-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'dev' }}
      role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
      aws_region: ${{ github.event.inputs.aws_region || 'eu-north-1' }}
      image_tag: ${{ needs.build.outputs.image_tag }}
      instance_ip: ${{ needs.terraform.outputs.instance_ip }}
    secrets: inherit
